*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 01.05.2021 at 23:42:51
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZCA_V_DEBUG.....................................*
FORM GET_DATA_ZCA_V_DEBUG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_DEBUG WHERE
(VIM_WHERETAB) .
    CLEAR ZCA_V_DEBUG .
ZCA_V_DEBUG-MANDT =
ZCA_DEBUG-MANDT .
ZCA_V_DEBUG-CODEPOINT =
ZCA_DEBUG-CODEPOINT .
ZCA_V_DEBUG-UNAME =
ZCA_DEBUG-UNAME .
ZCA_V_DEBUG-DATUM =
ZCA_DEBUG-DATUM .
ZCA_V_DEBUG-FROM_TIME =
ZCA_DEBUG-FROM_TIME .
ZCA_V_DEBUG-TO_TIME =
ZCA_DEBUG-TO_TIME .
ZCA_V_DEBUG-ACTIVE =
ZCA_DEBUG-ACTIVE .
<VIM_TOTAL_STRUC> = ZCA_V_DEBUG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCA_V_DEBUG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCA_V_DEBUG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCA_V_DEBUG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_DEBUG WHERE
  CODEPOINT = ZCA_V_DEBUG-CODEPOINT AND
  UNAME = ZCA_V_DEBUG-UNAME AND
  DATUM = ZCA_V_DEBUG-DATUM .
    IF SY-SUBRC = 0.
    DELETE ZCA_DEBUG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_DEBUG WHERE
  CODEPOINT = ZCA_V_DEBUG-CODEPOINT AND
  UNAME = ZCA_V_DEBUG-UNAME AND
  DATUM = ZCA_V_DEBUG-DATUM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_DEBUG.
    ENDIF.
ZCA_DEBUG-MANDT =
ZCA_V_DEBUG-MANDT .
ZCA_DEBUG-CODEPOINT =
ZCA_V_DEBUG-CODEPOINT .
ZCA_DEBUG-UNAME =
ZCA_V_DEBUG-UNAME .
ZCA_DEBUG-DATUM =
ZCA_V_DEBUG-DATUM .
ZCA_DEBUG-FROM_TIME =
ZCA_V_DEBUG-FROM_TIME .
ZCA_DEBUG-TO_TIME =
ZCA_V_DEBUG-TO_TIME .
ZCA_DEBUG-ACTIVE =
ZCA_V_DEBUG-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZCA_DEBUG ##WARN_OK.
    ELSE.
    INSERT ZCA_DEBUG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCA_V_DEBUG-UPD_FLAG,
STATUS_ZCA_V_DEBUG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCA_V_DEBUG.
  SELECT SINGLE * FROM ZCA_DEBUG WHERE
CODEPOINT = ZCA_V_DEBUG-CODEPOINT AND
UNAME = ZCA_V_DEBUG-UNAME AND
DATUM = ZCA_V_DEBUG-DATUM .
ZCA_V_DEBUG-MANDT =
ZCA_DEBUG-MANDT .
ZCA_V_DEBUG-CODEPOINT =
ZCA_DEBUG-CODEPOINT .
ZCA_V_DEBUG-UNAME =
ZCA_DEBUG-UNAME .
ZCA_V_DEBUG-DATUM =
ZCA_DEBUG-DATUM .
ZCA_V_DEBUG-FROM_TIME =
ZCA_DEBUG-FROM_TIME .
ZCA_V_DEBUG-TO_TIME =
ZCA_DEBUG-TO_TIME .
ZCA_V_DEBUG-ACTIVE =
ZCA_DEBUG-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCA_V_DEBUG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCA_V_DEBUG-CODEPOINT TO
ZCA_DEBUG-CODEPOINT .
MOVE ZCA_V_DEBUG-UNAME TO
ZCA_DEBUG-UNAME .
MOVE ZCA_V_DEBUG-DATUM TO
ZCA_DEBUG-DATUM .
MOVE ZCA_V_DEBUG-MANDT TO
ZCA_DEBUG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_DEBUG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_DEBUG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_DEBUG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
